language: node_js
os:
  - linux
  - windows
node_js:
  - lts/dubnium
  - lts/erbium
  - node
cache: npm
git:
  autocrlf: input
script:
  - npm run typecheck
  - npm run lint
  - npm run test -- --runInBand --coverage
after_success: cat coverage/lcov.info | npx coveralls
