language: node_js
node_js:
  - lts/dubnium
  - lts/erbium
  - node
os:
  - linux
  - windows
git:
  autocrlf: input
cache: npm
script:
  - npm run typecheck
  - npm run lint
  - npm run test -- --runInBand --coverage
after_success: cat coverage/lcov.info | npx coveralls
